openapi: 3.0.3
info:
  title: rest API for bugrtacker
  description: no description
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/bugtracker_war_exploded/'
    description: DEV-ENV
paths:
  /api/v1/issue:
    get:
      description
      responses:
        200:
          description: successfully retrieved all projects
          content:
            application/json:
              schema:
                type: array