package org.hetsold.bugtracker.facade;

import org.hetsold.bugtracker.dto.UserDTO;
import org.hetsold.bugtracker.model.User;

import java.util.List;
import java.util.stream.Collectors;

public class UserMapper {

    public static User getUser(UserDTO userDTO) {
        User user = null;
        if (userDTO != null) {
            user = new User();
            user.setUuid(userDTO.getUuid());
            mapDataFields(userDTO, user);
        }
        return user;
    }

    public static User getUserWithAutoGeneratedId(UserDTO userDTO) {
        User user = new User();
        mapDataFields(userDTO, user);
        return user;
    }

    private static void mapDataFields(UserDTO userDTO, User user) {
        user.setFirstName(userDTO.getFirstName());
        user.setLastName(userDTO.getLastName());
    }

    public static UserDTO getUserDTO(User user) {
        return new UserDTO(user);
    }

    public static List<UserDTO> getUserDTOS(List<User> userList) {
        return userList.stream().map(UserMapper::getUserDTO).collect(Collectors.toList());
    }
}