package org.hetsold.bugtracker.facade;

import org.hetsold.bugtracker.model.User;
import org.hetsold.bugtracker.model.UserDTO;

public class UserConvertor {

    public static User getUser(UserDTO userDTO) {
        User user = null;
        if (userDTO != null) {
            user = new User();
            user.setUuid(userDTO.getUuid());
            mapDataFields(userDTO, user);
        }
        return user;
    }

    public static User getUserWithAutoGeneratedId(UserDTO userDTO) {
        User user = new User();
        mapDataFields(userDTO, user);
        return user;
    }

    private static void mapDataFields(UserDTO userDTO, User user) {
        user.setFirstName(userDTO.getFirstName());
        user.setLastName(userDTO.getLastName());
    }

    public static UserDTO getUserDTO(User user) {
        return new UserDTO(user);
    }
}