package org.hetsold.bugtracker.service;

import org.hetsold.bugtracker.dao.UserDAO;
import org.hetsold.bugtracker.facade.UserConvertor;
import org.hetsold.bugtracker.model.User;
import org.hetsold.bugtracker.model.UserDTO;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;


@Service
@Transactional
public class DefaultUserService implements UserService {
    private UserDAO userDAO;

    public DefaultUserService() {
    }

    @Autowired
    public DefaultUserService(UserDAO userDAO) {
        this.userDAO = userDAO;
    }

    @Override
    public User save(User user) {
        if (user == null || user.getUuid().isEmpty()) {
            throw new IllegalArgumentException("incorrect user: user cannot be null");
        }
        userDAO.save(user);
        return user;
    }

    @Override
    @Transactional(propagation = Propagation.REQUIRED)
    public UserDTO registerUser(UserDTO userDTO) {
        if (userDTO == null || userDTO.getLastName().isEmpty() || userDTO.getFirstName().isEmpty()) {
            throw new IllegalArgumentException("incorrect user: user data required");
        }
        User savedUser = save(UserConvertor.getUserWithAutoGeneratedId(userDTO));
        return UserConvertor.getUserDTO(savedUser);
    }

    @Override
    @Transactional(propagation = Propagation.REQUIRED)
    public void updateUser(UserDTO userDTO) {
        User updatedUser = UserConvertor.getUser(userDTO);
        if (userDTO == null || userDTO.getUuid().isEmpty() || updatedUser == null) {
            throw new IllegalArgumentException("incorrect user: id is empty or user not exists");
        }
        User user = getUserById(userDTO.getUuid());
        user.update(updatedUser);
    }

    @Override
    @Transactional(propagation = Propagation.SUPPORTS, readOnly = true)
    public User getUserById(String uuid) {
        if (uuid.isEmpty()) {
            throw new IllegalArgumentException("incorrect user");
        }
        return userDAO.getUserById(uuid);
    }

    @Override
    @Transactional(propagation = Propagation.SUPPORTS, readOnly = true)
    public UserDTO getUserDTOById(String uuid) {
        if (uuid.isEmpty()) {
            throw new IllegalArgumentException("incorrect user");
        }
        return UserConvertor.getUserDTO(getUserById(uuid));
    }

    @Override
    @Transactional(propagation = Propagation.REQUIRED)
    public void delete(User user) {
        if (user == null) {
            throw new IllegalArgumentException("incorrect user: user cannot be null");
        }
        user = getUserById(user.getUuid());
        userDAO.delete(user);
    }

    @Override
    @Transactional(propagation = Propagation.REQUIRED)
    public void delete(UserDTO userDTO) {
        if (userDTO == null || userDTO.getUuid().isEmpty()) {
            throw new IllegalArgumentException("incorrect user: user id cannot be null");
        }
        delete(UserConvertor.getUser(userDTO));
    }

    @Override
    public List<UserDTO> getAllUsers() {
        return userDAO.listAll().stream().map(UserDTO::new).collect(Collectors.toList());
    }

    @Override
    public List<UserDTO> getUsers(int first, int count) {
        return userDAO.getUsers(first, count).stream().map(UserConvertor::getUserDTO).collect(Collectors.toList());
    }

    @Override
    public long getUserCount() {
        return userDAO.getUsersCount();
    }
}
