package org.hetsold.bugtracker.service;

import org.hetsold.bugtracker.dao.util.Contract;
import org.hetsold.bugtracker.dto.user.FullUserDTO;
import org.hetsold.bugtracker.dto.user.RegistrationDataDTO;
import org.hetsold.bugtracker.dto.user.UserDTO;
import org.hetsold.bugtracker.model.SecurityUserAuthority;

import java.util.List;
import java.util.Set;

public interface UserService {
    UserDTO registerByData(RegistrationDataDTO registrationDataDTO);

    UserDTO registerUser(FullUserDTO fullUserDTO);

    void updateUser(UserDTO userDTO);

    void updateEmail(UserDTO userDTO, String email);

    void updatePassword(UserDTO userDTO, String newPassword);

    void fullUserUpdate(FullUserDTO fullUserDTO);

    String getAutogeneratedPassword();

    void updateSecurityData(FullUserDTO fullUserDTO);

    void changeUserRoles(UserDTO userDTO, Set<SecurityUserAuthority> securityUserAuthorities);

    boolean isLoginTaken(String login);

    List<UserDTO> getUsers(Contract contract, int first, int count);

    long getUsersCount(Contract contract);

    void delete(UserDTO userDTO);

    UserDTO getUser(UserDTO userDTO);

    FullUserDTO getFullUserByUser(UserDTO userDTO);
}